### ISSUE TITLE
Method : I can't create BasicDefinition Tag in ODM.xml 

### ISSUE THREAD

**Issue by mugju** [swhume/odmlib_examples#2]
In the odm structure, there is a BasicDefination tag after the globalvariable tag
But i can't find method to create BasicDefination Tag

I looked it up in the example repository, but I couldn't find it, and if I missed anything about this, please let me know

**Comment by mugju** [comment]
I solved this problem by adding a BasicDef function

`

    def _add_basicdef_elements(self, basicdef):
        basicdef.MeasurementUnit = self._add_measurement()
        self._convert_elements()

    def _add_measurement(self):
        m1 = ODM.MeasurementUnit(OID="MU.1", Name = "MU.1")
        m1.Symbol = ODM.Symbol()
        m1.Symbol.TranslatedText.append(ODM.TranslatedText(_content="kg", lang="en"))
        m2 = ODM.MeasurementUnit(OID="MU.2", Name = "MU.2")
        m2.Symbol = ODM.Symbol()
        m2.Symbol.TranslatedText.append(ODM.TranslatedText(_content="mg", lang="en"))
        return [m1,m2]


`

in createdoc 
like this
`

    def create_document(self):
        root = ODM.ODM(FileOID="monkeypox", Granularity="Metadata", AsOfDateTime=self._set_datetime(),
                       CreationDateTime=self._set_datetime(), ODMVersion="1.3.2", FileType="Snapshot",
                       Originator="dongd", SourceSystem="odmlib", SourceSystemVersion="0.1")
        root.Study = self._add_study()
        self._add_basicdef_elements(root.Study[0].BasicDefinitions)
        root.Study[0].MetaDataVersion.append(ODM.MetaDataVersion(OID="MDV.DEMO-ODM-01", Name="Get Started MDV", Description="Get Started Demo"))
        self._add_mdv_elements(root.Study[0].MetaDataVersion[0])
        root.write_xml(self.odm_file)

`

**Comment by swhume** [comment]
Based on your original comment I added a test that did basically the same thing you did.

```
def test_basic_definitions(self):
    mu1 = ODM.MeasurementUnit(OID="MU.mg_2011-10-24", Name="mg")
    mu1.Symbol.TranslatedText.append(ODM.TranslatedText(_content="mg", lang="en"))
    mu2 = ODM.MeasurementUnit(OID="MU.ug_2011-10-24", Name="ug")
    mu2.Symbol.TranslatedText.append(ODM.TranslatedText(_content="ug", lang="en"))
    mu3 = ODM.MeasurementUnit(OID="MU.mL_2011-10-24", Name="mL")
    mu3.Symbol.TranslatedText.append(ODM.TranslatedText(_content="mL", lang="en"))
    self.study.BasicDefinitions.MeasurementUnit = [mu1, mu2, mu3]
    self.assertEqual(self.study.BasicDefinitions.MeasurementUnit[2].Name, "mL")
```

**Comment by swhume** [comment]
I can also update the example to include BasicDefinitions and follow your example. They are being deprecated in ODM v2.0 and I typically don't use them (though I know a few folks that do)

**Comment by mugju** [comment]
Thank you for your reply

I didn't know that BasicDefinitions deprecated in ODM 2.0 because i can't check ODM 2.0 document in offical site 
it's still in development status...
And I rarely had the chance to see a similar example(ODM.xml), so I didn't know that I didn't know usually not used BasicDefinition in ODM

Could you tell me when the 2.0 version will be released?

**Comment by swhume** [comment]
You can find the ODM v2.0 draft spec on the CDISC wiki (you'll need to create an account if you don't have one):
https://wiki.cdisc.org/display/ODM2/Operational+Data+Model+v2+Home

A draft version of ODM v2.0 will be released for Public Review this fall.

The reason the team decided to deprecate BasicDefinitions is that there are two ways to represent units. In SDTM it's a separate field and many use this approach in ODM - just create a separate variable for it. So, despite the fact that some folks do use BasicDefinitions, the decision was that it was better to have 1 way to represent units and most followed the SDTM pattern.
